apiVersion: v1
kind: Service
metadata:
  name: node-front-end-service
  labels:
    name: node-front-end-service
    app: qr-code-generator
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
  selector:
    name: node-front-end-pod
    app: qr-code-generator
