apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-api-deploy
  labels:
    name: python-api-deploy
    app: qr-code-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: python-api-pod
      app: qr-code-generator
  template:
    metadata:
      name: python-api-pod
      labels:
        name: python-api-pod
        app: qr-code-generator
    spec:
      containers:
        - name: python-api
          image: ghcr.io/human437/python-api-docker-image:main
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
